#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx restart
string="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=lMJvDi0KNlM? permanent;"
sudo sed -i "42i $string" /etc/nginx/sites-available/default
sudo service nginx restart
