#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
new_page = "\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=lMJvDi0KNlM"
sed -i "30i $new_page" /etc/nginx/sites-available/default
sudo service nginx restart
