#!/usr/bin/env bash
#  Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02
sudo apt-get -y update
sudo apt-get -y install nginx
header="\\\tadd_header X-Served-By $HOSTNAME;\n"
sudo sed -i "40i $header" /etc/nginx/sites-available/default
sudo service nginx start
