#!/usr/bin/env bash
#  Install your load balancer
apt-get update
apt-get -y install haproxy=1.6.\*
echo "ENABLED=1" >> /etc/default/haproxy
sed -i '/504.http/a \\nlisten http-in\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 2875-web-01 35.196.239.113:80 check\n\tserver 2875-web-02 3.94.160.0:80 check' /etc/haproxy/haproxy.cfg
sudo service haproxy start
