#!/usr/bin/env bash
#  Install your load balancer
sudo apt-get -y update
sudo apt-get install -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get install haproxy=2.0.\*
sudo sed -i '45 a \\nfrontend http_front\n\tbind *:80\n\tmode http\n\tdefault_backend http_back' /etc/haproxy/haproxy.cfg
sudo sed -i '55 a \\nbackend http_back\n\tbalance roundrobin\n\tserver 2875-web-01 35.196.239.113:80 check\n\tserver 2875-web-02 3.94.160.0:80 check' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
