#!/usr/bin/env bash
# Bash script that generates a MySQL dump and creates a compressed archive out of it.
mysqldump -u root --password="$1" -A -E > backup.sql
file=$(date +"%d-%m-%Y")
tar -czvf "$file".tar.gz backup.sql
