#!/usr/bin/env bash
# Process and PID file

sudo touch "/var/run/dhkscript.pid"

while True
do  
    trap 'echo "I hate the kill command"; sudo rm /var/run/holbertonscript.pid' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'sudo rm /var/run/holbertonscript.pid' SIGQUIT
    echo "To infinity and beyond"
    sleep 2
done
