#!/usr/bin/env bash
# Process and PID file

echo $$ sudo > /var/run/holbertonscript.pid
trap 'echo "I hate the kill command"; sudo rm /var/run/holbertonscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'sudo rm /var/run/holbertonscript.pid; exit' SIGQUIT
while True
do
    echo "To infinity and beyond"
    sleep 2
done
