#!/usr/bin/env bash
# Process and PID file

file=/var/run/holbertonscript.pid
sudo touch $file
sudo bash -c 'echo $$ > $file'
while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I hate the kill command"; sudo rm $file; exit' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'sudo rm $file; exit' SIGQUIT
done
