#!/usr/bin/env bash
# Bash script that displays "To infinity and beyond" and I am invincible!!!

infinity=0; while [ $infinity -eq 0 ]; do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "I am invincible!!!"' SIGTERM
done
