#!/usr/bin/env bash
# This script loops from 1 to 10
n=0; while (( n++ < 10));
do
    if [ $n = 4 ]
    then
        echo 'bad luck'
    elif [ $n = 8 ]
    then
        echo 'good luck'
    else
        echo 'Holberton School'
    fi
done
