#!/usr/bin/env bash
# This script is displaying  the time for 12 hours and 59 minutes
hours=0
while [ $hours -lt 13 ]
do
    echo "Hour: $hours"
    minutes=0
    while (( minutes++ < 59));
    do
        echo $minutes
    done
    let hours+=1
done
