#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements
# localhost resolves to 127.0.0.2
# localhost resolves to 127.0.0.2

cp /etc/hosts ~/tmp
sed -i 's/^127.0.0.1.*/127.0.0.2 localhost/g' ~/tmp
echo "8.8.8.8 facebook.com" >> ~/tmp
cp -f ~/tmp /etc/hosts
