#!/usr/bin/env bash
#  Run Nginx as Nginx
pkill apache2
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
